/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package AppGUI;


//import java.net.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author swany
 */
public class Y5Messanger extends javax.swing.JFrame {
boolean bflag;
//SocketServer ssob;
String cl,ml;
Connection conn = null;
 

 String driver = "com.mysql.jdbc.Driver";
 
//********************************************************************* 
 String url = "jdbc:mysql://localhost:3306/"; 
 String dbName = "db_wmb";
 
 String userName = "root";
 String password = "";
//*********************************************************************
 
NewLS newLS;
AddSub addSub;
Statement st,st1;
PreparedStatement preparedStmt ;

    /**
     * Creates new form Y5Messanger
     * @throws java.sql.SQLException
     */

public final void redraw() throws SQLException
{
      /* cl="<html>";
       for(int i=0;i<LoginNames.size();i++){
           cl=cl+LoginNames.elementAt(i)+"<br>";
}
                 cl=cl+"</html>";
                ClientList.setText(cl);
        */      /*  
                st.executeQuery("select ls_id,msg_body from tbl_message order by msg_creation_date desc");
                ResultSet rs = st.getResultSet();
                
                int tempInt= 0;
                ml="<html>";
                //rs1.next();
                while(rs.next()&& tempInt < 3){
                    st1.executeQuery("select ls_id,ls_name from tbl_ls");
                ResultSet rs1 = st1.getResultSet();
                    while(rs1.next()&& !(rs.getString("ls_id").equals(rs1.getString("ls_id"))))
                    {}
                    if(rs.getString("ls_id").equals(rs1.getString("ls_id"))) {
                        ml=ml+"<b>"+ rs1.getString("ls_name")+":</b><br>";
                    } else {
                    }
                    
            //ml=ml+"<b>"+ rs.getString("ls_name")+":</b><br>";
            ml=ml+ rs.getString("msg_body")+"<br><br>";
            tempInt++;
        }
                ml=ml+"</html>";
                /*String ml2 = ml.replaceAll(" ","");
                MessageList.setText(ml2);
                */    
               // MessageList.setText(ml);
               // jPanel1.repaint();
                //jPanel2.repaint();
                jPanel3.repaint();
                BroadcastButton.repaint();
                //ClientList.repaint();
               // MessageList.repaint();
}
    public Y5Messanger() throws SQLException, ClassNotFoundException, InstantiationException, IllegalAccessException, Exception {
        initComponents();
        bflag = false;
        //ssob=null;
        cl=new String();
        
        ml=new String();
        
        newLS= new NewLS ();
        addSub= new AddSub();
      try{
        Class.forName(driver).newInstance();
     conn = DriverManager.getConnection(url + dbName, userName, password);
    st = conn.createStatement();
    st1 = conn.createStatement();
    
      }catch(ClassNotFoundException | IllegalAccessException | InstantiationException | SQLException e){}
      redraw();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        NewLSButton = new javax.swing.JButton();
        BroadcastButton = new javax.swing.JButton();
        SubscriptionButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Y5Messanger");
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        NewLSButton.setText("Add New LS");
        NewLSButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewLSButtonActionPerformed(evt);
            }
        });

        BroadcastButton.setText("Start Broadcasting");
        BroadcastButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BroadcastButtonActionPerformed(evt);
            }
        });

        SubscriptionButton.setText("Subscription Expansion");
        SubscriptionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubscriptionButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel1.setText("Broadcaster for Y5M");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SubscriptionButton)
                            .addComponent(NewLSButton, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BroadcastButton, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel1)))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addComponent(BroadcastButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(NewLSButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(SubscriptionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BroadcastButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BroadcastButtonActionPerformed
        // TODO add your handling code here:
        if(bflag)
        {
            bflag=false;
            try {
                String query = "update tbl_broadcast set broadcast=0";
             preparedStmt = conn.prepareStatement(query);
             preparedStmt.executeUpdate();
            } catch (SQLException ex) {
                Logger.getLogger(Y5Messanger.class.getName()).log(Level.SEVERE, null, ex);
            }
             BroadcastButton.setText("Start Broadcast");
            try {
                redraw();
            } catch (SQLException ex) {
                Logger.getLogger(Y5Messanger.class.getName()).log(Level.SEVERE, null, ex);
            }
        }    
         else
        {
            try {
                bflag = true;
                //ssob=new SocketServer(this);
            try {
               // st.executeQuery("update tbl_broadcast set broadcast=1");
                String query = "update tbl_broadcast set broadcast=1";
             preparedStmt = conn.prepareStatement(query);
             preparedStmt.executeUpdate();
            } catch (SQLException ex) {
                Logger.getLogger(Y5Messanger.class.getName()).log(Level.SEVERE, null, ex);
            }    
            BroadcastButton.setText("Stop Broadcast");
            } 
            catch (Exception ex) {
                
                Logger.getLogger(Y5Messanger.class.getName()).log(Level.SEVERE, null, ex);
            }
   /*             finally{BroadcastButton.setText("Stop Broadcast");
                bflag=true;
                try {
                    redraw();
                } catch (SQLException ex) {
                    Logger.getLogger(Y5Messanger.class.getName()).log(Level.SEVERE, null, ex);
                }
}*/
            }
    }//GEN-LAST:event_BroadcastButtonActionPerformed

    private void NewLSButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewLSButtonActionPerformed
        // TODO add your handling code here:
        newLS.setVisible(true);
    }//GEN-LAST:event_NewLSButtonActionPerformed

    private void SubscriptionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubscriptionButtonActionPerformed
        // TODO add your handling code here:
        addSub.setVisible(true);
        
    }//GEN-LAST:event_SubscriptionButtonActionPerformed
    
    /**
     * @param args the command line arguments
     * @throws java.lang.Exception
     */
    public static void main(String args[]) throws Exception{
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Y5Messanger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                try {
                    new Y5Messanger().setVisible(true);
                } catch (        SQLException | ClassNotFoundException | InstantiationException | IllegalAccessException ex) {
                    Logger.getLogger(Y5Messanger.class.getName()).log(Level.SEVERE, null, ex);
                } catch (Exception ex) {
                    Logger.getLogger(Y5Messanger.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BroadcastButton;
    private javax.swing.JButton NewLSButton;
    private javax.swing.JButton SubscriptionButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables



}

